services:
  - type: web
    name: visa-website
    env: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python run.py
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: MONGODB_URL
        value: mongodb+srv://inshamanowar22_db_user:gCHLC03QnvtTtdLP@beyondborders.pmw8pvm.mongodb.net/
      - key: DATABASE_NAME
        value: beyondborder
    healthCheckPath: /health 